@php
$statusClasses = [
\App\Models\Status::PUBLISHED => 'success',
\App\Models\Status::ACTIVE => 'success',
\App\Models\Status::NOT_ACTIVE => 'warning',
\App\Models\Status::BLOCKED => 'danger',
\App\Models\Status::CLOSED => 'danger',
\App\Models\Status::OVERDUE => 'danger',
\App\Models\Status::NEW => 'primary',
\App\Models\Status::NOT_PUBLISHED => 'danger',
\App\Models\Status::PENDING => 'warning',
\App\Models\Status::CANCELLED => 'dark',
\App\Models\Status::EXPIRED => 'danger',
\App\Models\Status::TERMINATED => 'danger',
\App\Models\Status::RENEWED => 'success',
\App\Models\Status::PROCESSING => 'primary',
\App\Models\Status::DELIVERED => 'success',
\App\Models\Status::PARTIALLY_COMPLETED => 'info',
\App\Models\Status::COMPLETED => 'success',
\App\Models\Status::FAILED => 'danger',
\App\Models\Status::REVERSED => 'danger',
\App\Models\Status::PARTIALLY_REFUNDED => 'warning',
\App\Models\Status::REFUNDED => 'warning',
\App\Models\Status::FRAUD => 'danger',
\App\Models\Status::PREPAID => 'primary',
\App\Models\Status::USED => 'success',
\App\Models\Status::SCHEDULED => 'primary',
\App\Models\Status::SUSPENDED => 'warning',
\App\Models\Status::DEACTIVATED => 'warning',
\App\Models\Status::LIMITED_AVAILABILITY => 'warning',
\App\Models\Status::DISPUTED => 'danger',
\App\Models\Status::VOID => 'danger',
\App\Models\Status::ARCHIVED => 'dark',
\App\Models\Status::FILLED => 'success',
\App\Models\Status::REJECTED => 'danger',
\App\Models\Status::PAID => 'success',
\App\Models\Status::PARTIALLY_PAID => 'warning',
];
@endphp
{{ trim($statusClasses[$statusId] ?? 'danger') }}